	var memApp = (function() {
			var init = function(context) {
				member.init();
				onCreate();
			};
			var setContentView = function() {
				$('#h_admin').addClass('cursor');
				$('#p_con_footer').addClass('text_center').css('margin-left','16%').css('margin-right','0 auto').css('width','100%');
			};
			var onCreate = function() {
				setContentView();
				$('#pub_article').on('click','#m_rlogin',function(){
					$('#pub_article').html(SIGNIN);});
			};
			return {
				init : init,
				onCreate : onCreate,
				setContentView : setContentView
			}
})();

var nav = (function() {
	var init = function() {
		onCreate();
	};
	var setContentView = function() {
		
	};
	var onCreate = function() {
		setContentView();
	};
	return {
		init : init
	};
})();
var util = (function() {
	return {
		isNumber : function(value) {
			return typeof value === 'number' && isFinite(value);
		},
		pwChecker : function(value) {
			var pw_regex = /^.*(?=.{4,10})(?=.*[a-zA-Z0-9]).*$/;
			return pw_regex.test(value) ? "yes" : "no";
		},
		emailChecker : function(value) {
			 var regEmail = /([\w-\.]+)@((\[[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}\.)|(([\w-]+\.)+))([a-zA-Z]{2,4}|[0-9]{1,3})(\]?)$/;
			return regEmail.test(value) ? "yes" : "no";
		},
		phoneChecker : function(value) {
			 var regPhone = /^((01[1|6|7|8|9])[1-9]+[0-9]{6,7})|(010[1-9][0-9]{7})$/;
			return regPhone.test(value) ? "yes" : "no";
		}
	};
})();
var member = (function() {
	var init = function() {
		onCreate();
	};
	var setContentView = function() {
	};
	var onCreate = function() {
		setContentView();
		$('#pub_header').on('click','#h_logo_u',function(){
			$('#pub_header').load(app.context()+ '/member/logined/header');
			$('#pub_article').load(app.context()+ '/member/logined/main');
			
		});
		$('#pub_article').on('click','#m_signup_e',function(){
		$.ajax({
			url : app.context() + '/member/m_signupE',
			success : function(data) {
				if (data.message === "success") {
					$('#pub_article').empty().html(SINGUPEMAIL);
				} else {
					alert('실패 {} : ');
				}
			},
			error : function(x, h, m) {
				alert('에러' + m);
			}
		});
		});
			$('#signup_phone').keyup(					
					function() {
							if (util.phoneChecker($('#signup_phone').val()) === 'yes'){
								$('font[name=phone_check]').text('');
								$('font[name=phone_check]').html("올바른전화번호입니다.").css('color', 'green');
							} else {
								$('font[name=phone_check]').text('');
								$('font[name=phone_check]').html("올바르지않은전화번호입니다.").css('color', 'red');
							}
					}); 
			$('#pub_article').on('click','#m_bt_signup',function(e){
										e.preventDefault();
										var sign_info = {'email' : $('#signup_email').val(),
												'pw' : $('#signup_pw').val(),
												'name' : $('#signup_name').val(),
												'phone' : $('#signup_phone').val(),
												'month' : $('#signup_month').val(),
												'day' : $('#signup_day').val(),
												'year' : $('#signup_year').val()};
										$.ajax({
											url : app.context()+ '/member/signupE',
											type : 'post',
											contentType : 'application/json',
											data : JSON.stringify(sign_info),
											dataType : 'json',
											success : function(data) {
												if (data.message.toUpperCase() === 'SUCCESS') {
													alert('성공!!!!!');
													$('#pub_article').empty().html(SIGNIN);
												} else {
													alert('회원가입 시 알수없는 에러가 발생했습니다.');
												}
											},
											error : function(x,s,m) {
												alert('회원가입 시 에러발생 마지막!!!!'+ m);
											}
								});
						});
		
			$('#pub_header').on('click','#m_logout',function(){
					location.href=app.context()+'/member/logout'
			});
			$('#m_signup').click(function(){
				$('#pub_article').empty().html(SIGNUP);});
			$('#m_signin').click(function(){
				$('#pub_article').html(SIGNIN);
				$('#user-login-btn').click(function(e){
				e.preventDefault();
				$.ajax({
					url : app.context()+'/member/signin',
					type : 'get',
					data : {'email' : $('#signin_email').val(),
							'pw' : $('#signin_password').val()},
					dataType : 'json',
					async : false,
					success : function(data){
						if (data.email==='admin') {
							location.href = app.context()+'/admin/main';
						} else {
							$('#pub_header').empty().load(app.context()+ '/member/logined/header');
							$('#pub_article').empty().load(app.context()+ '/member/logined/main');
							$('.input-daterange').datepicker({language: "kr", format: "yyyy/mm/dd",startDate: "+0d"});
						}
					},
					error : function(x,s,m){alert('error '+m+'==로그인정보가 다릅니다..');}
				});
				});
			});
			//onCreate
				};
				return {
					init : init
				};
				//Member
			})();
var SINGUPEMAIL=
	'<%@ page language="java" contentType="text/html; charset=UTF-8" pageEncoding="UTF-8"%>'
	+'<link href="https://a1.muscache.com/airbnb/static/packages/common_o2.1-80868f847ed03c82dab1f44270c61862.css" media="all" rel="stylesheet" type="text/css" />'
	+'<link href="https://a2.muscache.com/airbnb/static/packages/common-dcb5379dabd7d5fd274a603dacdf9239.css" media="all" rel="stylesheet" type="text/css" />'
	+'<link href="https://a0.muscache.com/airbnb/static/signinup-054b06337494ba9bc92696dc56d55dcb.css" media="screen" rel="stylesheet" type="text/css" />'
	+'<meta name="twitter:widgets:csp" content="on">'
	+'<meta name="viewport" content="width=device-width, initial-scale=1">'
	 +'<section style="width:30%;margin-left:35%;padding-top: 5%;padding-bottom:5%">'
	+'<h3 style="color:red;text-align:center"><strong>이메일로 회원가입</strong></h3>'
	+'<div class="control-group space-1">'
	+'<input type="email" name="email" id="signup_email" placeholder="이메일 주소" class="decorative-input inspectletIgnore"/>'
	+'</div>'
	+'<div class="control-group space-1">'
	+'<div>'
	+'<input type="password" id="signup_pw" name="pw" placeholder="비밀번호를 입력해주세요" class="decorative-input inspectletIgnore">'
	+'</div>'
	+'</div>'
	+'<div class="control-group space-1">'
	+'<input type="text" name="name" id="signup_name" placeholder="이름" class="decorative-input" value="">'
	+'</div>'
	+'<div class="control-group space-1" >'
	+'<strong>전화번호</strong>'
	+'<input type="text" name="phone" id="signup_phone" placeholder="-제외"class="decorative-input inspectletIgnore"><font name="phone_check" size="2" color="red"/>'
	+'</div>'
	+'<div class="control-group space-top-3 space-1">'
	+'<strong>생일</strong>'
	+'<strong id="birthday-signup-form-question-trigger"><i class=icon icon-question></i></strong>'
	+'<div class="tooltip tooltip-bottom-middle signup-login-form__tooltip" role="tooltip" aria-hidden="true" data-trigger="#birthday-signup-form-question-trigger" data-position="top">'
	+'<p class="panel-body">회원 가입을 하시려면 만 18세 이상이어야 합니다. 생일은 다른 회원에게는 공개되지 않습니다.</p>'
	+'</div>'
	+'</div>'
	+'<div class="control-group row row-condensed space-2">'
	+'<div class="col-sm-5">'
	+'<div class="select va-container-h">'
	+'<select id="signup_month" name="month">'
	+'<option value="">월</option>'
	+'<option value="01">1월</option>'
	+'<option value="02">2월</option>'
	+'<option value="03">3월</option>'
	+'<option value="04">4월</option>'
	+'<option value="05">5월</option>'
	+'<option value="06">6월</option>'
	+'<option value="07">7월</option>'
	+'<option value="08">8월</option>'
	+'<option value="09">9월</option>'
	+'<option value="10">10월</option>'
	+'<option value="11">11월</option>'
	+'<option value="12">12월</option>'
	+'</select>'
	+'</div>'
	+'</div>'
	+'<div class="col-sm-3">'
	+'<div class="select va-container-h">'
	+'<select id="signup_day" name="day">'
	+'<option value="">일</option>'
	+'<option value="01">1</option>'
	+'<option value="02">2</option>'
	+'<option value="03">3</option>'
	+'<option value="04">4</option>'
	+'<option value="05">5</option>'
	+'<option value="06">6</option>'
	+'<option value="07">7</option>'
	+'<option value="08">8</option>'
	+'<option value="09">9</option>'
	+'<option value="10">10</option>'
	+'<option value="11">11</option>'
	+'<option value="12">12</option>'
	+'<option value="13">13</option>'
	+'<option value="14">14</option>'
	+'<option value="15">15</option>'
	+'<option value="16">16</option>'
	+'<option value="17">17</option>'
	+'<option value="18">18</option>'
	+'<option value="19">19</option>'
	+'<option value="20">20</option>'
	+'<option value="21">21</option>'
	+'<option value="22">22</option>'
	+'<option value="23">23</option>'
	+'<option value="24">24</option>'
	+'<option value="25">25</option>'
	+'<option value="26">26</option>'
	+'<option value="27">27</option>'
	+'<option value="28">28</option>'
	+'<option value="29">29</option>'
	+'<option value="30">30</option>'
	+'<option value="31">31</option>'
	+'</select>'
	+'</div>'
	+'</div>'
	+'<div class="col-sm-4">'
	+'<div class="select va-container-h">'
	+'<select id="signup_year" name="year">'
	+'<option value="">년</option>'
	+'<option value="2016">2016</option>'
	+'<option value="2015">2015</option>'
	+'<option value="2014">2014</option>'
	+'<option value="2013">2013</option>'
	+'<option value="2012">2012</option>'
	+'<option value="2011">2011</option>'
	+'<option value="2010">2010</option>'
	+'<option value="2009">2009</option>'
	+'<option value="2008">2008</option>'
	+'<option value="2007">2007</option>'
	+'<option value="2006">2006</option>'
	+'<option value="2005">2005</option>'
	+'<option value="2004">2004</option>'
	+'<option value="2003">2003</option>'
	+'<option value="2002">2002</option>'
	+'<option value="2001">2001</option>'
	+'<option value="2000">2000</option>'
	+'<option value="1999">1999</option>'
	+'<option value="1998">1998</option>'
	+'<option value="1997">1997</option>'
	+'<option value="1996">1996</option>'
	+'<option value="1995">1995</option>'
	+'<option value="1994">1994</option>'
	+'<option value="1993">1993</option>'
	+'<option value="1992">1992</option>'
	+'<option value="1991">1991</option>'
	+'<option value="1990">1990</option>'
	+'<option value="1989">1989</option>'
	+'<option value="1988">1988</option>'
	+'<option value="1987">1987</option>'
	+'<option value="1986">1986</option>'
	+'<option value="1985">1985</option>'
	+'<option value="1984">1984</option>'
	+'<option value="1983">1983</option>'
	+'<option value="1982">1982</option>'
	+'<option value="1981">1981</option>'
	+'<option value="1980">1980</option>'
	+'<option value="1979">1979</option>'
	+'<option value="1978">1978</option>'
	+'<option value="1977">1977</option>'
	+'<option value="1976">1976</option>'
	+'<option value="1975">1975</option>'
	+'<option value="1974">1974</option>'
	+'<option value="1973">1973</option>'
	+'<option value="1972">1972</option>'
	+'<option value="1971">1971</option>'
	+'<option value="1970">1970</option>'
	+'<option value="1969">1969</option>'
	+'<option value="1968">1968</option>'
	+'<option value="1967">1967</option>'
	+'<option value="1966">1966</option>'
	+'<option value="1965">1965</option>'
	+'<option value="1964">1964</option>'
	+'<option value="1963">1963</option>'
	+'<option value="1962">1962</option>'
	+'<option value="1961">1961</option>'
	+'<option value="1960">1960</option>'
	+'<option value="1959">1959</option>'
	+'<option value="1958">1958</option>'
	+'<option value="1957">1957</option>'
	+'<option value="1956">1956</option>'
	+'<option value="1955">1955</option>'
	+'<option value="1954">1954</option>'
	+'<option value="1953">1953</option>'
	+'<option value="1952">1952</option>'
	+'<option value="1951">1951</option>'
	+'<option value="1950">1950</option>'
	+'<option value="1949">1949</option>'
	+'<option value="1948">1948</option>'
	+'<option value="1947">1947</option>'
	+'<option value="1946">1946</option>'
	+'<option value="1945">1945</option>'
	+'<option value="1944">1944</option>'
	+'<option value="1943">1943</option>'
	+'<option value="1942">1942</option>'
	+'<option value="1941">1941</option>'
	+'<option value="1940">1940</option>'
	+'<option value="1939">1939</option>'
	+'<option value="1938">1938</option>'
	+'<option value="1937">1937</option>'
	+'<option value="1936">1936</option>'
	+'<option value="1935">1935</option>'
	+'<option value="1934">1934</option>'
	+'<option value="1933">1933</option>'
	+'<option value="1932">1932</option>'
	+'<option value="1931">1931</option>'
	+'<option value="1930">1930</option>'
	+'<option value="1929">1929</option>'
	+'<option value="1928">1928</option>'
	+'<option value="1927">1927</option>'
	+'<option value="1926">1926</option>'
	+'<option value="1925">1925</option>'
	+'<option value="1924">1924</option>'
	+'<option value="1923">1923</option>'
	+'<option value="1922">1922</option>'
	+'<option value="1921">1921</option>'
	+'<option value="1920">1920</option>'
	+'<option value="1919">1919</option>'
	+'<option value="1918">1918</option>'
	+'<option value="1917">1917</option>'
	+'<option value="1916">1916</option>'
	+'<option value="1915">1915</option>'
	+'<option value="1914">1914</option>'
	+'<option value="1913">1913</option>'
	+'<option value="1912">1912</option>'
	+'<option value="1911">1911</option>'
	+'<option value="1910">1910</option>'
	+'<option value="1909">1909</option>'
	+'<option value="1908">1908</option>'
	+'<option value="1907">1907</option>'
	+'<option value="1906">1906</option>'
	+'<option value="1905">1905</option>'
	+'<option value="1904">1904</option>'
	+'<option value="1903">1903</option>'
	+'<option value="1902">1902</option>'
	+'<option value="1901">1901</option>'
	+'<option value="1900">1900</option>'
	+'<option value="1899">1899</option>'
	+'<option value="1898">1898</option>'
	+'<option value="1897">1897</option>'
	+'<option value="1896">1896</option>'
	+'</select>'
	+'</div>'
	+'</div>'
	+'</div>'
	+'<input  type="submit" value="회원가입" class="btn btn-primary btn-block signup-login-form__btn-xl btn-large" id="m_bt_signup"></input>'
	+'<div class="panel-body js-login-footer signup-login-form__extra-panel-body">'
	+'<div class="clearfix">'
	+'<span class="signup-login-form__switch-copy">'
	+'<a class="modal-link link-to-login-in-signup"> 이미 에어비앤비 계정이 있나요?</a></span>'
	+'<a id="m_rlogin" class="modal-link link-to-login-in-signup btn btn-default signup-login-form__btn-rausch-border signup-login-form__btn-font-normal signup-login-form__switch-button">로그인</a></div></div>'
	+'<form accept-charset="UTF-8" id="facebook_form" method="post"><div style="margin:0;padding:0;display:inline"><input name="utf8" type="hidden" value="&#x2713;" /><input name="authenticity_token" type="hidden" value="V4$.airbnb.co.kr$XckjA4Yc7Gw$1oHuhMsM5L5M2087Mo4ColJz6qNhHfmzeMjcx1Om8lw=" /></div>'
	+'<input id="airlock_id" name="airlock_id" type="hidden" value="" />'
	+'</form>'
	+'</section>' 
	var DASHBOARD = 
	'<div id="pub_article">'	
	+'<div class="page-container-responsive space-top-4 space-4">'
	+'<div style="padding-top:5%" class="row">'
	+'<div class="col-md-3">'
	+'<div class="panel space-4">'
	+'<div class="media media-photo-block">'
	+'<a href="${context}/member/show/" title="View Profile"><img alt="Rachel" class="img-responsive" height="190" src='+app.img()+'/member/hollyQueen.jpg title="rachel" width="190" /></a>'
	+'</div>'
	+'<div class="panel-body">'
	+'<h2 class="text-center">Rachel</h2>'
	+'<ul class="list-unstyled text-center">'
	+'<li><a href="${context}/member/show/">View Profile</a></li>'
	+'<li><a href="${context}/member/edit/" id="edit-profile">Edit Profile</a>'
	+'</li>'
	+'</ul>'
	+'</div>'
	+'</div>'
	+'<div class="panel space-4 verifications-panel-vertical ">'
	+'<div class="panel-header row">'
	+'<div class="pull-left">'
	+'Verifications'
	+'</div>'
	+'<div class="pull-right">'
	+'<i class="icon icon-question" id="tooltip-trigger"></i>'
	+'<div class="tooltip tooltip-right-middle" role="tooltip" aria-hidden="true" data-trigger="#tooltip-trigger" data-sticky="true">'
	+'<p class="panel-body">'
	+'  Verifications help build trust between guests and hosts and can make booking easier.<a href="/help/article/336">Learn more »</a>'
	+'</p>'
	+'</div>'
	+'</div>'
	+'</div>'
	+'<div class="panel-body">'
	+'<ul class="list-unstyled ">'
	+'<li class="row row-condensed">'
	+'<div class="media">'
	+'  <i class="icon icon-ok icon-lima h3 pull-left"></i>'
	+'  <div class="media-body">'
	+'    <div>'
	+'Email address'
	+' </div>'
	+' <div class="text-muted">'
	+'Verified'
	+'</div>'
	+'  </div>'
	+'</div>'
	+'</li>'
	+'<li class="row row-condensed">'
	+'<div class="media">'
	+'  <i class="icon icon-ok icon-lima h3 pull-left"></i>'
	+'  <div class="media-body">'
	+' <div>Phone number</div>'
	+' <div class="text-muted">(▒▒▒) ▒▒▒-▒▒45</div>'
	+'  </div>'
	+'</div>'
	+'</li>'
	+'<li class="row row-condensed">'
	+'<div class="media">'
	+'  <i class="icon icon-ok icon-lima h3 pull-left"></i>'
	+'  <div class="media-body">'
	+' <div>'
	+'   Reviewed'
	+' </div>'
	+' <div class="text-muted">'
	+'   2 Reviews'
	+' </div>'
	+'  </div>'
	+'</div>'
	+'</li>'
	+'<li class="row row-condensed">'
	+'<div class="media">'
	+'  <i class="icon icon-ok icon-lima h3 pull-left"></i>'
	+'  <div class="media-body">'
	+' <div>'
	+' Personal info'
	+' </div>'
	+' <div class="text-muted">'
	+'   Verified'
	+' </div>'
	+'  </div>'
	+'</div>'
	+'</li>'
	+'</ul>'
	+'	<a href="#">'
	+'Add Verifications'
	+'</a>'
	+'</div>'
	+'</div>'
	+'<div class="panel space-4">'
	+'<div class="panel-header">Quick Links</div>'
	+'<div class="panel-body">'
	+'  <ul class="list-unstyled">'
	+' <li class="space-2">'
	+'   <a href="${context}/member/trips">Upcoming Trips</a>'
	+' </li>'
	+' <li class="space-2">'
	+'   <a href="#">Hosting on Airbnb</a>'
	+' </li>'
	+' <li class="space-2">'
	+'   <a href="#">Traveling on Airbnb</a>'
	+' </li>'
	+' <li class="space-2">'
	+'   <a href="#">Help Center</a>'
	+' </li>'
	+'  </ul>'
	+'</div>'
	+'</div>'
	+'	</div>'
	+'	<div class="col-md-9">'
	+'<div class="panel space-4">'
	+'<div class="panel-header">'
	+'  Messages (1 new)'
	+'</div>'
	+'  <ul class="list-layout">'
	+'<li class="panel-body thread-read thread" id="thread_172155785">'
	+'<div class="row">'
	+'<div class="col-3">'
	+'<div class="row row-table">'
	+'<div class="col-5">'
	+'  <a href="#" target="_blank"><img alt="Ajit" class="img-round" height="50" src="https://a1.muscache.com/im/users/863155/profile_pic/1311564603/original.jpg?aki_policy=profile_small" title="Ajit" width="50" /></a>'
	+'</div>'
	+'<div class="col-7">'
	+'  Ajit'
	+'  <br/>'
	+'  Feb 16'
	+'</div>'
	+'</div>'
	+'</div>'
	+'<a href="#" class="link-reset text-muted">'
	+'<div class="col-7">'
	+'	  Oknp. Sorry to hear about that. :( You were going t...<br/>'
	+'<span class="text-muted">'
	+' <span class=street-address>Norwalk Lane</span>, <span class=locality>Austin</span>, <span class=region>TX</span>'
	+'   (Mar 9 - 16, 2016)'
	+'</span>'
	+'</div>'
	+'</a>    <div class="col-2">'
	+'<span class="label label-gray label-info">Canceled</span>'
	+'<br/>'
	+'$1588'
	+'</div>'
	+'	</div>'
	+'</li>'
	+'<li class="panel-body thread-read thread" id="thread_166764939">'
	+'<div class="row">'
	+'<div class="col-3">'
	+'<div class="row row-table">'
	+'<div class="col-5">'
	+'<a href="#" target="_blank"><img alt="Richard" class="img-round" height="50" src="https://a0.muscache.com/im/users/15396185/profile_pic/1400523583/original.jpg?aki_policy=profile_small" title="Richard" width="50" /></a>'
	+'</div>'
	+'<div class="col-7">'
	+'Richard'
	+'  <br/>'
	+'  Feb 09'
	+'</div>'
	+'</div>'
	+'</div>'
	+'<a href="#" class="link-reset text-muted">'
	+'<div class="col-7">:)<br/>'
	+'<span class="text-muted">'
	+'<span class=street-address>Angell Street</span>, <span class=locality>Providence</span>, <span class=region>RI</span>'
	+'(Feb 4 - 8, 2016)'
	+'</span>'
	+'</div>'
	+'</a>    <div class="col-2">'
	+'<span class="label label-green label-success">Accepted</span>'
	+'<br/>'
	+'$567'
	+'</div>'
	+'</div>'
	+'</li>'
	+'<li class="panel-body thread-read thread" id="thread_166762954">'
	+'<div class="row">'
	+'<div class="col-3">'
	+'<div class="row row-table">'
	+'<div class="col-5">'
	+'<a href="#" target="_blank"><img alt="Elizabeth" class="img-round" height="50" src="https://a2.muscache.com/im/pictures/cb376bbf-677e-499a-8d2a-16e14c8e883c.jpg?aki_policy=profile_small" title="Elizabeth" width="50" /></a>'
	+'</div>'
	+'<div class="col-7">Elizabeth<br/>'
	+'Jan 20'
	+'</div>'
	+'</div>'
	+'</div>'
	+'<a href="#" class="link-reset text-muted">'
	+'<div class="col-7">'
	+'Hi I&#x27;m a Brown alum visiting for recruiting events ...'
	+'<br/>'
	+'<span class="text-muted">'
	+'<span class=street-address>Benefit Street</span>, <span class=locality>Providence</span>, <span class=region>RI</span>'
	+'(Feb 4 - 8, 2016)'
	+'</span>'
	+'</div>'
	+'</a>    <div class="col-2">'
	+'<span class="label label-gray label-info">Canceled</span>'
	+'<br/>'
	+'$480'
	+'</div>'
	+'</div>'
	+'</li>'
	+'<li class="panel-body  thread" id="thread_97044264">'
	+'<div class="row">'
	+'<div class="col-3">'
	+'<div class="row row-table">'
	+'<div class="col-5">'
	+'<a href="#" target="_blank"><img alt="Christiane" class="img-round" height="50" src="https://a2.muscache.com/im/users/2702141/profile_pic/1442827721/original.jpg?aki_policy=profile_small" title="Christiane" width="50" /></a>'
	+'</div>'
	+'<div class="col-7">'
	+'Christian'
	+'<br/>'
	+'06/07/2015'
	+'</div>'
	+'</div>'
	+'</div>'
	+'<a href="#" class="link-reset ">'
	+'<div class="col-7">'
	+'<strong>'
	+'Hi! I&#x27;m on the way and will be there in 15'
	+'</strong>'
	+'<br/>'
	+'<span class="text-muted">'
	+'<span class=street-address>West 15th Street</span>, <span class=locality>New York</span>, <span class=region>NY</span>'
	+'(Jun 7 - 12, 2015)'
	+'</span>'
	+'</div>'
	+'</a>    <div class="col-2">'
	+'<span class="label label-green label-success">Accepted</span>'
	+'<br/>'
	+'$1724'
	+'</div>'
	+'</div>'
	+'</li>'
	+'<li class="panel-body thread-read thread" id="thread_97044261">'
	+'<div class="row">'
	+'<div class="col-3">'
	+'<div class="row row-table">'
	+'<div class="col-5">'
	+'<a href="#" target="_blank"><img alt="Elnaz" class="img-round" height="50" src="https://a2.muscache.com/im/users/15447043/profile_pic/1401289639/original.jpg?aki_policy=profile_small" title="Elnaz" width="50" /></a>'
	+'</div>'
	+'<div class="col-7">'
	+'  Elnaz'
	+'  <br/>'
	+'  05/07/2015'
	+'</div>'
	+'</div>'
	+'</div>'
	+'<a href="#" class="link-reset text-muted">'
	+'<div class="col-7">Ok!<br/>'
	+'<span class="text-muted">'
	+'<span class=street-address>West 21st Street</span>, <span class=locality>New York</span>, <span class=region>NY</span>'
	+'(Jun 8 - 12, 2015)'
	+'</span>'
	+'</div>'
	+'</a><div class="col-2">'
	+'<span class="label label-gray label-info">Canceled</span>'
	+'<br/>'
	+'$1750'
	+'</div>'
	+'</div>'
	+'</li>'
	+'  </ul>'
	+'<div class="panel-body">'
	+'<a href="${context}/member/inbox">All messages</a>'
	+'</div>'
	+'</div>'
	+'</div>'
	+'</div>'
	+'</div>'
	+'</div>';
	var EDIT = 
	'<link href="https://a2.muscache.com/airbnb/static/packages/common-86180c1646b448bc4a69535df81ff5de.css" media="all" rel="stylesheet" type="text/css">'
	+'<link href="https://a1.muscache.com/airbnb/static/packages/address_widget-4f18ee66a37930ce1c93c8f33690c7b0.css" media="screen" rel="stylesheet" type="text/css">'
	+'<link href="https://a2.muscache.com/airbnb/static/packages/phonenumbers-67b13441cd68e5c9161e38a0dab88b54.css" media="screen" rel="stylesheet" type="text/css">'
	+'<link href="https://a2.muscache.com/airbnb/static/business_travel/quick_enroll-9fe44fac8aa94516d93764b9b4e57633.css" media="screen" rel="stylesheet" type="text/css">'
	+'<link href="https://a1.muscache.com/airbnb/static/packages/edit_profile-ac1fc053a07a8229d28854f4afdc24e6.css" media="screen" rel="stylesheet" type="text/css">'
	+'<div class="page-container-responsive space-top-4 space-4">'
	+'<div style="padding-top:5%" class="row">'
	+'<div class="col-md-9">'
	+'<div id="dashboard-content">'
	+'<form accept-charset="UTF-8" action=""'
	+'enctype="multipart/form-data"'
	+'id="update_form" method="post">'
	+'<div style="margin: 0; padding: 0; display: inline">'
	+'<input name="utf8" type="hidden" value="✓"><input'
	+'name="authenticity_token" type="hidden"'
	+'value="V4$.airbnb.com$u8jr5IsblaY$yYcqVcVU2Lwk3OuMuF2orePeKN9E08huP-LjKGvlPdw=">'
	+'</div>'
	+'<div class="panel space-4">'
	+'<div class="panel-header">Required</div>'
	+'<div class="panel-body">'
	+'<div class="row row-condensed space-4">'
	+'<label class="text-right col-sm-3" for="user_first_name">'
	+'First Name </label>'
	+'<div class="col-sm-9">'
	+'<input id="user_first_name" name="user[first_name]" size="30"'
	+'type="text" value="Hello"'
	+'style="background-image: url(&quot;data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAABAAAAAQCAYAAAAf8/9hAAABHklEQVQ4EaVTO26DQBD1ohQWaS2lg9JybZ+AK7hNwx2oIoVf4UPQ0Lj1FdKktevIpel8AKNUkDcWMxpgSaIEaTVv3sx7uztiTdu2s/98DywOw3Dued4Who/M2aIx5lZV1aEsy0+qiwHELyi+Ytl0PQ69SxAxkWIA4RMRTdNsKE59juMcuZd6xIAFeZ6fGCdJ8kY4y7KAuTRNGd7jyEBXsdOPE3a0QGPsniOnnYMO67LgSQN9T41F2QGrQRRFCwyzoIF2qyBuKKbcOgPXdVeY9rMWgNsjf9ccYesJhk3f5dYT1HX9gR0LLQR30TnjkUEcx2uIuS4RnI+aj6sJR0AM8AaumPaM/rRehyWhXqbFAA9kh3/8/NvHxAYGAsZ/il8IalkCLBfNVAAAAABJRU5ErkJggg==&quot;); background-repeat: no-repeat; background-attachment: scroll; background-size: 16px 18px; background-position: 98% 50%; cursor: auto;">'
	+'</div>'
	+'</div>'
	+'<div class="row row-condensed space-4">'
	+'<div class="col-sm-9">'
	+'<div class="text-muted space-top-1">We use this data for'
	+'analysis and never share it with other users.</div>'
	+'</div>'
	+'</div>'
	+'<div class="row row-condensed space-4">'
	+'<label class="text-right col-sm-3" for="user_birthdate">'
	+'Birth Date <i class="icon icon-lock icon-ebisu"'
	+'data-behavior="tooltip" aria-label="Private"></i>'
	+'</label>'
	+'<div class="col-sm-9">'
	+'<div class="select">'
	+'<select id="user_birthdate_2i" name="user[birthdate(2i)]">'
	+'<option value="01">January</option>'
	+'<option value="02">February</option>'
	+'<option value="03">March</option>'
	+'<option value="04">April</option>'
	+'<option value="05">May</option>'
	+'<option selected="selected" value="08">May</option>'
	+'<option value="07">July</option>'
	+'<option value="08">August</option>'
	+'<option value="09">September</option>'
	+'<option value="10">October</option>'
	+'<option value="11">November</option>'
	+'<option value="12">December</option>'
	+'</select>'
	+'</div>'
	+'<div class="select">'
	+'<select id="user_birthdate_3i" name="user[birthdate(3i)]">'
	+'<option value="1">1</option>'
	+'<option value="2">2</option>'
	+'<option value="3">3</option>'
	+'<option value="4">4</option>'
	+'<option value="5">5</option>'
	+'<option selected="selected" value="6">6</option>'
	+'<option value="7">7</option>'
	+'<option value="8">8</option>'
	+'<option value="9">9</option>'
	+'<option value="10">10</option>'
	+'<option value="11">11</option>'
	+'<option value="12">12</option>'
	+'<option value="13">13</option>'
	+'<option value="14">14</option>'
	+'<option value="15">15</option>'
	+'<option value="16">16</option>'
	+'<option value="17">17</option>'
	+'<option value="18">18</option>'
	+'<option value="19">19</option>'
	+'<option value="20">20</option>'
	+'<option value="21">21</option>'
	+'<option value="22">22</option>'
	+'<option value="23">23</option>'
	+'<option value="24">24</option>'
	+'<option value="25">25</option>'
	+'<option value="26">26</option>'
	+'<option value="27">27</option>'
	+'<option value="28">28</option>'
	+'<option value="29">29</option>'
	+'<option value="30">30</option>'
	+'<option value="31">31</option>'
	+'</select>'
	+'</div>'
	+'<div class="select">'
	+'<select id="user_birthdate_1i" name="user[birthdate(1i)]">'
	+'<option value="1998">1998</option>'
	+'<option value="1997">1997</option>'
	+'<option value="1996">1996</option>'
	+'<option value="1995">1995</option>'
	+'<option value="1994">1994</option>'
	+'<option value="1993">1993</option>'
	+'<option value="1992">1992</option>'
	+'<option value="1991">1991</option>'
	+'<option selected="selected" value="1990">1990</option>'
	+'<option value="1989">1989</option>'
	+'<option value="1988">1988</option>'
	+'<option value="1987">1987</option>'
	+'<option value="1986">1986</option>'
	+'<option value="1985">1985</option>'
	+'<option value="1984">1984</option>'
	+'<option value="1983">1983</option>'
	+'<option value="1982">1982</option>'
	+'<option value="1981">1981</option>'
	+'<option value="1980">1980</option>'
	+'<option value="1979">1979</option>'
	+'<option value="1978">1978</option>'
	+'<option value="1977">1977</option>'
	+'<option value="1976">1976</option>'
	+'<option value="1975">1975</option>'
	+'<option value="1974">1974</option>'
	+'<option value="1973">1973</option>'
	+'<option value="1972">1972</option>'
	+'<option value="1971">1971</option>'
	+'<option value="1970">1970</option>'
	+'<option value="1969">1969</option>'
	+'<option value="1968">1968</option>'
	+'<option value="1967">1967</option>'
	+'<option value="1966">1966</option>'
	+'<option value="1965">1965</option>'
	+'<option value="1964">1964</option>'
	+'<option value="1963">1963</option>'
	+'<option value="1962">1962</option>'
	+'<option value="1961">1961</option>'
	+'<option value="1960">1960</option>'
	+'<option value="1959">1959</option>'
	+'<option value="1958">1958</option>'
	+'<option value="1957">1957</option>'
	+'<option value="1956">1956</option>'
	+'<option value="1955">1955</option>'
	+'<option value="1954">1954</option>'
	+'<option value="1953">1953</option>'
	+'<option value="1952">1952</option>'
	+'<option value="1951">1951</option>'
	+'<option value="1950">1950</option>'
	+'<option value="1949">1949</option>'
	+'<option value="1948">1948</option>'
	+'<option value="1947">1947</option>'
	+'<option value="1946">1946</option>'
	+'<option value="1945">1945</option>'
	+'<option value="1944">1944</option>'
	+'<option value="1943">1943</option>'
	+'<option value="1942">1942</option>'
	+'<option value="1941">1941</option>'
	+'<option value="1940">1940</option>'
	+'<option value="1939">1939</option>'
	+'<option value="1938">1938</option>'
	+'<option value="1937">1937</option>'
	+'<option value="1936">1936</option>'
	+'<option value="1935">1935</option>'
	+'<option value="1934">1934</option>'
	+'<option value="1933">1933</option>'
	+'<option value="1932">1932</option>'
	+'<option value="1931">1931</option>'
	+'<option value="1930">1930</option>'
	+'<option value="1929">1929</option>'
	+'<option value="1928">1928</option>'
	+'<option value="1927">1927</option>'
	+'<option value="1926">1926</option>'
	+'<option value="1925">1925</option>'
	+'<option value="1924">1924</option>'
	+'<option value="1923">1923</option>'
	+'<option value="1922">1922</option>'
	+'<option value="1921">1921</option>'
	+'<option value="1920">1920</option>'
	+'<option value="1919">1919</option>'
	+'<option value="1918">1918</option>'
	+'<option value="1917">1917</option>'
	+'<option value="1916">1916</option>'
	+'</select>'
	+'</div>'
	+'<div class="text-muted space-top-1">The magical day you'
	+'were dropped from the sky by a stork. We use this data for'
	+'analysis and never share it with other users.</div>'
	+'</div>'
	+'</div>'
	+'<div class="row row-condensed space-4">'
	+'<label class="text-right col-sm-3" for="user_email">'
	+'Email Address <i class="icon icon-lock icon-ebisu"'
	+'data-behavior="tooltip" aria-label="Private"></i>'
	+'</label>'
	+'<div class="col-sm-9">'
	+'<input id="user_email" name="user[email]" size="30"'
	+'type="text" value="Hello@gmail.com">'
	+'<div class="text-muted space-top-1">'
	+'We won’t share your private email address with other Airbnb'
	+'users.'
	+'</div>'
	+'</div>'
	+'</div>'
	+'<td class="remove-container"><a'
	+'href="https://www.airbnb.com/phone_numbers/delete/11625073"'
	+'data-authenticity-token="V4$.airbnb.com$u8jr5IsblaY$yYcqVcVU2Lwk3OuMuF2orePeKN9E08huP-LjKGvlPdw="'
	+'class="remove" title="Remove"> <i'
	+'class="icon icon-remove"></i>'
	+'</a></td>'
	+'</tr>'
	+'</tbody>'
	+'</table>'
	+'</div>'
	+'Airbnb is built on relationships. Help other people get to'
	+'know you.<br>'
	+'<br>Tell them about the things you like: What are 5'
	+'things you can’t live without? Share your favorite travel'
	+'destinations, books, movies, shows, music, food.<br>'
	+'<br>Tell them what it’s like to have you as a guest or'
	+'host: What’s your style of traveling? Of Airbnb hosting?<br>'
	+'<br>Tell them about you: Do you have a life motto?'
	+'</div>'
	+'<div class="panel-padding panel-body">'
	+'<div class="textInput text-input-container" id="inputEmail">'
	+'<input class="decorative-input" id="confirm_password" name="password" placeholder="Password" type="password">'
	+'<div class="clearfix control-group space-top-2 text-right">'
	+'</div>'
	+'</div>'
	+'</div>'
	+'<div class="panel-footer">'
	+'<button type="submit" class="btn btn-primary">'
	+'Confirm Password'
	+'</button>'
	+'</div>'
	+'</div>'
	+'</div>'
	+'</div>'
	+'</div>'
	+'<div class="panel space-4">'
	+'<button style="margin-left:40%;" type="submit" class="btn btn-primary btn-large">'
	+'Save'
	+'</button>'
	+'</div>'
	+'</div>'
	+'</div>'
	+'</form>'
	+'<div class="modal reauth-modal" role="dialog" aria-hidden="true">'
	+'<div class="modal-table">'
	+'<div class="modal-cell">'
	+'<div class="modal-content signup">'
	+'<div id="reauthenticate_container">'
	+'<form accept-charset="UTF-8" action="?" id="reauth_form" method="post"><div style="margin:0;padding:0;display:inline"><input name="utf8" type="hidden" value="✓"><input name="authenticity_token" type="hidden" value="V4$.airbnb.com$u8jr5IsblaY$yYcqVcVU2Lwk3OuMuF2orePeKN9E08huP-LjKGvlPdw="></div>'
	+'<h3 class="panel-header panel-header-gray">'
	+'Confirm Password to Continue'
	+'</h3>'
	+'<div class="panel-header alert alert-header alert-with-icon alert-danger" hidden="">'
	+'<i class="icon icon-alert-alt alert-icon"></i>'
	+'<span class="reauth-error"></span>'
	+'</div>'
	+'</form></div>'
	+'</div>'
	+'</div>'
	+'</div>'
	+'</div>'
	+'</div>'
	+'</div>'
	+'</div>'
	+'</div>';
	var SIGNIN =
	'<link href="https://a1.muscache.com/airbnb/static/packages/common_o2.1-f8a73ee0d4378e3442aa7772f248998e.css" media="all" rel="stylesheet" type="text/css">'
	+'<link href="https://a0.muscache.com/airbnb/static/packages/common-c8bdb80ccb067b0069b7dfafcf08edbf.css" media="all" rel="stylesheet" type="text/css">'
	+'<link href="https://a0.muscache.com/airbnb/static/signinup-054b06337494ba9bc92696dc56d55dcb.css" media="screen" rel="stylesheet" type="text/css">'
	+'<title>Log In / Sign Up to Airbnb</title>'
	+'<link rel="image_src" href="https://a2.muscache.com/airbnb/static/logos/belo-200x200-4d851c5b28f61931bf1df28dd15e60ef.png">'
	+'<link rel="search" type="application/opensearchdescription+xml" href="/opensearch.xml" title="Airbnb">'
	+'<link rel="apple-touch-icon" href="https://a0.muscache.com/airbnb/static/icons/apple-touch-icon-76x76-3b313d93b1b5823293524b9764352ac9.png">'
	+'<link rel="apple-touch-icon" sizes="76x76" href="https://a0.muscache.com/airbnb/static/icons/apple-touch-icon-76x76-3b313d93b1b5823293524b9764352ac9.png">'
	+'<link rel="apple-touch-icon" sizes="120x120" href="https://a1.muscache.com/airbnb/static/icons/apple-touch-icon-120x120-52b1adb4fe3a8f825fc4b143de12ea4b.png">'
	+'<link rel="apple-touch-icon" sizes="152x152" href="https://a0.muscache.com/airbnb/static/icons/apple-touch-icon-152x152-7b7c6444b63d8b6ebad9dae7169e5ed6.png">'
	+'<link rel="apple-touch-icon" sizes="180x180" href="https://a2.muscache.com/airbnb/static/icons/apple-touch-icon-180x180-bcbe0e3960cd084eb8eaf1353cf3c730.png">'
	+'<link rel="icon" sizes="192x192" href="https://a1.muscache.com/airbnb/static/icons/android-icon-192x192-c0465f9f0380893768972a31a614b670.png">'
	+'<link rel="shortcut icon" sizes="76x76" type="image/x-icon" href="https://a1.muscache.com/airbnb/static/logotype_favicon-21cc8e6c6a2cca43f061d2dcabdf6e58.ico">'
	+'<div class="flash-container"></div>'
	+'<main  id="site-content" role="main">'
	+'<div style="padding-top:80px;" class="page-container-responsive page-container-auth space-top-4 space-8">'
	+'<div class="panel signup-login-form__container" id="signup-modal-content">'
	+'<div class="panel-body signup-login-form__extra-panel-body first">'
	+'<a href="/oauth_connect?from=facebook_login&amp;redirect_params[action]=edit&amp;redirect_params[controller]=users&amp;redirect_params[id]=27430889&amp;redirect_params[section]=media&amp;service=facebook" class="btn icon-btn btn-block signup-login-form__btn-xl btn-large space-1 btn-facebook js-facebook-auth">'
	+'<span class="icon-container">'
	+'<i class="icon icon-facebook"></i>'
	+'</span>'
	+'<span class="text-container">'
	+'Log in with Facebook'
	+'</span>'
	+'</a>'
	+'<a href="/oauth_connect?from=google_login&amp;redirect_params[action]=edit&amp;redirect_params[controller]=users&amp;redirect_params[id]=27430889&amp;redirect_params[section]=media&amp;service=google" class="btn icon-btn btn-block signup-login-form__btn-xl btn-large space-1 btn-google js-google-auth">'
	+'<!--?xml version="1.0" encoding="UTF-8" standalone="no"?-->'
	+'<svg version="1.1" xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink" class="icon icon-google-image">'
	+'<defs></defs>'
	+'<g id="Page-1" stroke="none" stroke-width="1" fill="none" fill-rule="evenodd">'
	+'<g id="super-g">'
	+'<path d="M9,3.48 C10.69,3.48 11.83,4.21 12.48,4.82 L15.02,2.34 C13.46,0.89 11.43,0 9,0 C5.48,0 2.44,2.02 0.96,4.96 L3.87,7.22 C4.6,5.05 6.62,3.48 9,3.48 L9,3.48 L9,3.48 Z" id="Shape" fill="#EA4335"></path>'
	+'<path d="M17.64,9.2 C17.64,8.46 17.58,7.92 17.45,7.36 L9,7.36 L9,10.7 L13.96,10.7 C13.86,11.53 13.32,12.78 12.12,13.62 L14.96,15.82 C16.66,14.25 17.64,11.94 17.64,9.2 L17.64,9.2 L17.64,9.2 Z" id="Shape" fill="#4285F4"></path>'
	+'<path d="M3.88,10.78 C3.69,10.22 3.58,9.62 3.58,9 C3.58,8.38 3.69,7.78 3.87,7.22 L0.96,4.96 C0.35,6.18 0,7.55 0,9 C0,10.45 0.35,11.82 0.96,13.04 L3.88,10.78 L3.88,10.78 L3.88,10.78 Z" id="Shape" fill="#FBBC05"></path>'
	+'<path d="M9,18 C11.43,18 13.47,17.2 14.96,15.82 L12.12,13.62 C11.36,14.15 10.34,14.52 9,14.52 C6.62,14.52 4.6,12.95 3.88,10.78 L0.97,13.04 C2.45,15.98 5.48,18 9,18 L9,18 L9,18 Z" id="Shape" fill="#34A853"></path>'
	+'<path d="M0,0 L18,0 L18,18 L0,18 L0,0 L0,0 Z" id="Shape"></path>'
	+'</g>'
	+'</g>'
	+'<image class="google-logo-svg-fallback" src="https://a1.muscache.com/airbnb/static/signinup/google_icon_2x-745c2280e5004d4c90e3ca4e60e3f677.png" xlink:href="">'
	+'</image></svg>'
	+'<span class="text-container">'
	+'Log in with Google'
	+'</span>'
	+'</a>'
	+'<div class="signup-or-separator">'
	+'<span class="h6 signup-or-separator--text">or</span>'
	+'<hr>'
	+'</div>'
	+'<form accept-charset="UTF-8" class="login-form " method="post"><div style="margin:0;padding:0;display:inline"><input name="utf8" type="hidden" value="✓"><input name="authenticity_token" type="hidden" value="V4$.airbnb.com$8kD0U_r6huU$_A7dC0ezPK2q6KxilrIO4xTJM8uNYL3ZJJPXlD1XjbA="></div>'
	+'<input id="from" name="from" type="hidden" value="email_login">'
	+'<input id="airlock_id" name="airlock_id" type="hidden" value="">'
	+'<input id="redirect_params_action" name="redirect_params[action]" type="hidden" value="edit">'
	+'<input id="redirect_params_controller" name="redirect_params[controller]" type="hidden" value="users">'
	+'<input id="redirect_params_id" name="redirect_params[id]" type="hidden" value="27430889">'
	+'<input id="redirect_params_section" name="redirect_params[section]" type="hidden" value="media">'
	+'<div class="control-group space-1">'
	+'<input class="decorative-input inspectletIgnore" id="signin_email" name="email" placeholder="Email Address" type="email" autocomplete="off" style="cursor: auto;">'
	+'</div>'
	+'<div class="control-group space-2">'
	+'<input class="decorative-input inspectletIgnore" id="signin_password" name="password" placeholder="Password" type="password" autocomplete="off" style="cursor: auto;">'
	+'</div>'
	+'<div class="clearfix space-1">'
	+'<label for="remember_me2" class="checkbox remember-me space-1">'
	+'<input type="checkbox" name="remember_me" id="remember_me2" value="true" class="remember_me">'
	+'Remember me'
	+'</label>'
	+'<a href="/forgot_password" class="forgot-password pull-right" data-from="email">Forgot password?</a>'
	+'</div>'
	+'<div id="airlock-inline-container"></div>'
	+'<button type="submit" class="btn btn-block signup-login-form__btn-xl btn-primary btn-large" id="user-login-btn">'
	+'Log in'
	+'</button>'
	+'</form>'
	+'</div>'
	+'</div>'
	+'<form accept-charset="UTF-8" action="/authenticate" id="facebook_form" method="post"><div style="margin:0;padding:0;display:inline"><input name="utf8" type="hidden" value="✓"><input name="authenticity_token" type="hidden" value="V4$.airbnb.com$8kD0U_r6huU$_A7dC0ezPK2q6KxilrIO4xTJM8uNYL3ZJJPXlD1XjbA="></div>'
	+'<input id="redirect_params_action" name="redirect_params[action]" type="hidden" value="edit">'
	+'<input id="redirect_params_controller" name="redirect_params[controller]" type="hidden" value="users">'
	+'<input id="redirect_params_id" name="redirect_params[id]" type="hidden" value="27430889">'
	+'<input id="redirect_params_section" name="redirect_params[section]" type="hidden" value="media">'
	+'<input id="retry_params_action" name="retry_params[action]" type="hidden" value="edit">'
	+'<input id="retry_params_controller" name="retry_params[controller]" type="hidden" value="users">'
	+'<input id="retry_params_id" name="retry_params[id]" type="hidden" value="27430889">'
	+'<input id="retry_params_section" name="retry_params[section]" type="hidden" value="media">'
	+'<input id="airlock_id" name="airlock_id" type="hidden" value="">'
	+'</form>'
	+'</div></main>';
var SIGNUP =
	'<link href="https://a1.muscache.com/airbnb/static/packages/common_o2.1-f8a73ee0d4378e3442aa7772f248998e.css" media="all" rel="stylesheet" type="text/css">'
	+'<link href="https://a0.muscache.com/airbnb/static/packages/common-c8bdb80ccb067b0069b7dfafcf08edbf.css" media="all" rel="stylesheet" type="text/css">'
	+'<link href="https://a0.muscache.com/airbnb/static/signinup-054b06337494ba9bc92696dc56d55dcb.css" media="screen" rel="stylesheet" type="text/css">'
	+'<link rel="image_src" href="https://a2.muscache.com/airbnb/static/logos/belo-200x200-4d851c5b28f61931bf1df28dd15e60ef.png">'
	+'<link rel="search" type="application/opensearchdescriptionxml" href="/opensearch.xml" title="Airbnb">'
	+'<link rel="apple-touch-icon" href="https://a0.muscache.com/airbnb/static/icons/apple-touch-icon-76x76-3b313d93b1b5823293524b9764352ac9.png">'
	+'<link rel="apple-touch-icon" sizes="76x76" href="https://a0.muscache.com/airbnb/static/icons/apple-touch-icon-76x76-3b313d93b1b5823293524b9764352ac9.png">'
	+'<link rel="apple-touch-icon" sizes="120x120" href="https://a1.muscache.com/airbnb/static/icons/apple-touch-icon-120x120-52b1adb4fe3a8f825fc4b143de12ea4b.png">'
	+'<link rel="apple-touch-icon" sizes="152x152" href="https://a0.muscache.com/airbnb/static/icons/apple-touch-icon-152x152-7b7c6444b63d8b6ebad9dae7169e5ed6.png">'
	+'<link rel="apple-touch-icon" sizes="180x180" href="https://a2.muscache.com/airbnb/static/icons/apple-touch-icon-180x180-bcbe0e3960cd084eb8eaf1353cf3c730.png">'
	+'<link rel="icon" sizes="192x192" href="https://a1.muscache.com/airbnb/static/icons/android-icon-192x192-c0465f9f0380893768972a31a614b670.png">'
	+'<link rel="shortcut icon" sizes="76x76" type="image/x-icon" href="https://a1.muscache.com/airbnb/static/logotype_favicon-21cc8e6c6a2cca43f061d2dcabdf6e58.ico">'
	+'<div class="flash-container"></div>'
	+'<main  id="site-content" role="main">'
	+'<div style="padding-top:80px;" class="page-container-responsive page-container-auth space-top-4 space-8">'
	+'<div class="panel signup-login-form__container" id="signup-modal-content">'
	+'<div class="panel-body signup-login-form__extra-panel-body first">'
	+'<a href="/oauth_connect?from=facebook_login&amp;redirect_params[action]=edit&amp;redirect_params[controller]=users&amp;redirect_params[id]=27430889&amp;redirect_params[section]=media&amp;service=facebook" class="btn icon-btn btn-block signup-login-form__btn-xl btn-large space-1 btn-facebook js-facebook-auth">'
	+'<span class="icon-container">'
	+'<i class="icon icon-facebook"></i>'
	+'</span>'
	+'<span class="text-container">'
	+'Sign Up with Facebook'
	+'</span>'
	+'</a>'
	+'<a href="/oauth_connect?from=google_login&amp;redirect_params[action]=edit&amp;redirect_params[controller]=users&amp;redirect_params[id]=27430889&amp;redirect_params[section]=media&amp;service=google" class="btn icon-btn btn-block signup-login-form__btn-xl btn-large space-1 btn-google js-google-auth">'
	+'<!--?xml version="1.0" encoding="UTF-8" standalone="no"?-->'
	+'<svg version="1.1" xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink" class="icon icon-google-image">'
	+'<defs></defs>'
	+'<g id="Page-1" stroke="none" stroke-width="1" fill="none" fill-rule="evenodd">'
	+'<g id="super-g">'
	+'<path d="M9,3.48 C10.69,3.48 11.83,4.21 12.48,4.82 L15.02,2.34 C13.46,0.89 11.43,0 9,0 C5.48,0 2.44,2.02 0.96,4.96 L3.87,7.22 C4.6,5.05 6.62,3.48 9,3.48 L9,3.48 L9,3.48 Z" id="Shape" fill="#EA4335"></path>'
	+'<path d="M17.64,9.2 C17.64,8.46 17.58,7.92 17.45,7.36 L9,7.36 L9,10.7 L13.96,10.7 C13.86,11.53 13.32,12.78 12.12,13.62 L14.96,15.82 C16.66,14.25 17.64,11.94 17.64,9.2 L17.64,9.2 L17.64,9.2 Z" id="Shape" fill="#4285F4"></path>'
	+'<path d="M3.88,10.78 C3.69,10.22 3.58,9.62 3.58,9 C3.58,8.38 3.69,7.78 3.87,7.22 L0.96,4.96 C0.35,6.18 0,7.55 0,9 C0,10.45 0.35,11.82 0.96,13.04 L3.88,10.78 L3.88,10.78 L3.88,10.78 Z" id="Shape" fill="#FBBC05"></path>'
	+'<path d="M9,18 C11.43,18 13.47,17.2 14.96,15.82 L12.12,13.62 C11.36,14.15 10.34,14.52 9,14.52 C6.62,14.52 4.6,12.95 3.88,10.78 L0.97,13.04 C2.45,15.98 5.48,18 9,18 L9,18 L9,18 Z" id="Shape" fill="#34A853"></path>'
	+'<path d="M0,0 L18,0 L18,18 L0,18 L0,0 L0,0 Z" id="Shape"></path>'
	+'</g>'
	+'</g>'
	+'<image class="google-logo-svg-fallback" src="https://a1.muscache.com/airbnb/static/signinup/google_icon_2x-745c2280e5004d4c90e3ca4e60e3f677.png" xlink:href="">'
	+'</image></svg>'
	+'<span class="text-container">'
	+'Sign Up with Google'
	+'</span>'
	+'</a>'
	+'<div class="signup-or-separator">'
	+'<span class="h6 signup-or-separator--text">or</span>'
	+'<hr>'
	+'</div>'
	+'<div class="clearfix space-1">'
	+'<label for="remember_me2" class="checkbox remember-me space-1">'
	+'<input type="checkbox" name="remember_me" id="remember_me2" value="true" class="remember_me">'
	+'Remember me'
	+'</label>'
	+'<a href="/forgot_password" class="forgot-password pull-right" data-from="email">Forgot password?</a>'
	+'</div>'
	+'<div  id="m_signup_e"class="btn btn-block signup-login-form__btn-xl btn-primary btn-large" >'
	+'Sign Up with Email'
	+'</div>'
	+'</form>'
	+'</div>'
	+'</div>'
	+'</div></main>'
	
	
	